# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-05 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.TextField(verbose_name='Direcci\xf3n')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='uploads/restarurante', verbose_name='Imagen')),
                ('precio', models.CharField(max_length=100, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
    ]
